# Generated by Django 4.0.4 on 2022-11-27 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atencion',
            fields=[
                ('id_atencion', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('motivo', models.CharField(max_length=200)),
                ('descripcion', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'atencion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BitacoraCirugia',
            fields=[
                ('id_bitacora_cirugia', models.BigIntegerField(primary_key=True, serialize=False)),
                ('detalle', models.CharField(max_length=3000)),
                ('fecha', models.DateField()),
                ('hora', models.DateTimeField()),
            ],
            options={
                'db_table': 'bitacora_cirugia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id_cargo', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'cargo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cirugia',
            fields=[
                ('id_cirugia', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
            ],
            options={
                'db_table': 'cirugia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id_ciudad', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'ciudad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id_comuna', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'comuna',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleUnidad',
            fields=[
                ('id_detalle_unidad', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'detalle_unidad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DisponibilidadPabellon',
            fields=[
                ('id_disponibilidad_pabellon', models.BigIntegerField(primary_key=True, serialize=False)),
                ('disponible', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'disponibilidad_pabellon',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id_evaluacion', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('atencion', models.CharField(max_length=50)),
                ('riesgo', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'evaluacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id_medico', models.IntegerField(primary_key=True, serialize=False)),
                ('rut', models.IntegerField(unique=True)),
                ('dv', models.CharField(max_length=1)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido_p', models.CharField(max_length=50)),
                ('apellido_m', models.CharField(max_length=50)),
                ('genero', models.CharField(max_length=1)),
                ('fecha_nac', models.DateField()),
                ('telefono', models.IntegerField()),
                ('correo', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=2000)),
                ('direccion', models.CharField(max_length=100)),
                ('administrador', models.CharField(max_length=1)),
                ('habilitado', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'medico',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id_modulo', models.IntegerField(primary_key=True, serialize=False)),
                ('hora_ini', models.DateField()),
                ('hora_fin', models.DateField()),
            ],
            options={
                'db_table': 'modulo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pabellon',
            fields=[
                ('id_pabellon', models.IntegerField(primary_key=True, serialize=False)),
                ('piso', models.IntegerField()),
                ('numeracion', models.IntegerField()),
                ('habilitado', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'pabellon',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id_paciente', models.BigIntegerField(primary_key=True, serialize=False)),
                ('rut', models.IntegerField()),
                ('dv', models.CharField(max_length=1)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido_p', models.CharField(max_length=50)),
                ('apellido_m', models.CharField(max_length=50)),
                ('genero', models.CharField(max_length=1)),
                ('fecha_nac', models.DateField()),
                ('telefono', models.IntegerField()),
                ('correo', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'paciente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProgramacionCirugia',
            fields=[
                ('id_reserva_cirugia', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('notificado', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'programacion_cirugia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id_recurso', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
                ('cantidad_actual', models.IntegerField()),
                ('cantidad_maxima', models.IntegerField()),
                ('cantidad_peligro', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'recurso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id_region', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'region',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReservaPabellon',
            fields=[
                ('id_reserva', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
            ],
            options={
                'db_table': 'reserva_pabellon',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id_unidad', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'unidad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReservaRecurso',
            fields=[
                ('cantidad', models.IntegerField()),
                ('id_recurso', models.OneToOneField(db_column='id_recurso', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.recurso')),
            ],
            options={
                'db_table': 'reserva_recurso',
                'managed': False,
            },
        ),
    ]
