# Generated by Django 4.0.4 on 2022-11-27 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atencion',
            options={'managed': False, 'verbose_name_plural': 'Atenciones'},
        ),
        migrations.AlterModelOptions(
            name='bitacoracirugia',
            options={'managed': False, 'verbose_name_plural': 'Bitacoras de cirugia'},
        ),
        migrations.AlterModelOptions(
            name='cargo',
            options={'managed': False, 'verbose_name_plural': 'Cargos'},
        ),
        migrations.AlterModelOptions(
            name='cirugia',
            options={'managed': False, 'verbose_name_plural': 'Cirugias'},
        ),
        migrations.AlterModelOptions(
            name='ciudad',
            options={'managed': False, 'verbose_name_plural': 'Ciudades'},
        ),
        migrations.AlterModelOptions(
            name='comuna',
            options={'managed': False, 'verbose_name_plural': 'Comunas'},
        ),
        migrations.AlterModelOptions(
            name='detalleunidad',
            options={'managed': False, 'verbose_name_plural': 'Detalle unidades'},
        ),
        migrations.AlterModelOptions(
            name='disponibilidadpabellon',
            options={'managed': False, 'verbose_name_plural': 'Disponibilidad pabellones'},
        ),
        migrations.AlterModelOptions(
            name='evaluacion',
            options={'managed': False, 'verbose_name_plural': 'Evaluaciones'},
        ),
        migrations.AlterModelOptions(
            name='medico',
            options={'managed': False, 'verbose_name_plural': 'Medicos'},
        ),
        migrations.AlterModelOptions(
            name='modulo',
            options={'managed': False, 'verbose_name_plural': 'Modulos'},
        ),
        migrations.AlterModelOptions(
            name='pabellon',
            options={'managed': False, 'verbose_name_plural': 'Pabellones'},
        ),
        migrations.AlterModelOptions(
            name='paciente',
            options={'managed': False, 'verbose_name_plural': 'Pacientes'},
        ),
        migrations.AlterModelOptions(
            name='programacioncirugia',
            options={'managed': False, 'verbose_name_plural': 'Programacion de cirugias'},
        ),
        migrations.AlterModelOptions(
            name='recurso',
            options={'managed': False, 'verbose_name_plural': 'Recursos'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'managed': False, 'verbose_name_plural': 'Regiones'},
        ),
        migrations.AlterModelOptions(
            name='reservapabellon',
            options={'managed': False, 'verbose_name_plural': 'Reserva pabellones'},
        ),
        migrations.AlterModelOptions(
            name='reservarecurso',
            options={'managed': False, 'verbose_name_plural': 'Reserva recursos'},
        ),
        migrations.AlterModelOptions(
            name='unidad',
            options={'managed': False, 'verbose_name_plural': 'Unidades'},
        ),
    ]
